<form action="/user/insert" method="POST">
    <label for="name">Name: </label><br>
    <input required type="text" name="name" id="name"><br><br>

    <label for="email">Email: </label><br>
    <input required type="email" name="email" id="email"><br><br>

    <label for="password">Password: </label><br>
    <input required type="password" name="password" id="password"><br><br>

    <button>Go!</button>
</form>